# Archivo stack.yaml completo con configuración Nix y librerías comunes

# Resolver: especifica la versión de GHC y el conjunto de paquetes a usar
resolver: nightly-2024-08-17
# Paquetes del proyecto
packages:
  - .

# Dependencias adicionales no incluidas en el resolver
# Estos son paquetes de Haskell que no están en el snapshot especificado
extra-deps:
  - aeson-2.2.3.0@rev:1
  - http-conduit-2.3.8
  - conduit-1.3.4.2
  - http-client-0.7.11
  - servant-0.19
  - servant-server-0.4.4
  - wai-3.2.3
  - warp-3.3.20
  - amqp-0.23.0
  - hspec-2.11.9

# Configuración de Nix
nix:
  # Habilita el uso de Nix
  enable: false
  # Si es true, solo usa los paquetes especificados en 'packages'
  pure: false
  # Paquetes del sistema necesarios
  # Estos son dependencias del sistema operativo, no paquetes de Haskell
  packages:
    - zlib
    # Añade aquí otros paquetes del sistema que necesites

# Opciones de GHC para todos los targets
ghc-options:
  "$everything": -O2 -Wall

# Control de la versión de GHC
system-ghc: true
# Descomenta la siguiente línea si necesitas una versión específica de GHC
compiler: ghc-9.8.2

# Configuración para permitir versiones más nuevas de paquetes
allow-newer: true

# Configuración para construir en paralelo
jobs: 4

# Especifica una versión mínima de stack
require-stack-version: ">=2.7.0"

# Configuración de instalación del proyecto
install-ghc: true
skip-ghc-check: false

# Configuración adicional de compilación
build:
  library-profiling: false
  executable-profiling: false
  haddock: true
  haddock-deps: false
  copy-bins: false
  prefetch: false
  keep-going: false

